# -*- coding: utf-8 -*-
# Manuel Düzeltilmiş Veri Dosyası - Kategoriye Göre ID Aralıkları Düzenlendi
# Laptop: 1001-1999
# Telefon: 2001-2999
# Masaüstü: 3001-3999

from typing import List, Dict, Any

products: List[Dict[str, Any]] = [
    # --- LAPTOP (1001 - 1999) ---
    {
        "id": 1001,
        "category": "Laptop",
        "name": "LENOVOLegion Pro 7 Core U9 2.7g 32gb 1TB Rtx5070tı 16'' Oled Gaming Notebook 83f5004qtr",
        "brand": "Lenovo",
        "price": 149999,
        "url": "https://www.trendyol.com/lenovo/legion-pro-7-core-u9-2-7g-32gb-1tb-rtx5070ti-16-oled-gaming-notebook-83f5004qtr-p-987438255",
        "specs": {}
    },
    {
        "id": 1002,
        "category": "Laptop",
        "name": "MSICYBORG 15 A13VF-892XTR Intel Core i7 13620H 16GB 512GB SSD RTX4060 Freedos 15.6\" FHD 144Hz Taşınabilir Bilgisayar",
        "brand": "MSI",
        "price": 45590,
        "url": "https://www.hepsiburada.com/msi-cyborg-15-a13vf-892xtr-intel-core-i7-13620h-16gb-512gb-ssd-rtx4060-freedos-15-6-fhd-144hz-tasinabilir-bilgisayar-pm-HBC00005T87HS",
        "specs": {}
    },
    {
        "id": 1003,
        "category": "Laptop",
        "name": "CasperExcalibur G870 Intel Core i7 13620H 16GB 1TB SSD RTX4050 Freedos 15.6\" 165Hz Taşınabilir Bilgisayar G870.1362-BFA0X-C",
        "brand": "Casper",
        "price": 43999,
        "url": "https://www.hepsiburada.com/casper-excalibur-g870-intel-core-i7-13620h-16gb-1tb-ssd-rtx4050-freedos-15-6-165hz-tasinabilir-bilgisayar-g870-1362-bfa0x-c-pm-HBC00003ZQ8HX",
        "specs": {}
    },
    {
        "id": 1004,
        "category": "Laptop",
        "name": "CasperExcalibur G770 Intel Core i7 12700H 16GB 500GB SSD RTX3050 Freedos 15.6\" Taşınabilir Bilgisayar G770.1270-BVJ0X-B",
        "brand": "Casper",
        "price": 33999,
        "url": "https://www.hepsiburada.com/casper-excalibur-g770-intel-core-i7-12700h-16gb-500gb-ssd-rtx3050-freedos-15-6-tasinabilir-bilgisayar-g770-1270-bvj0x-b-pm-HBC00002R2PMU",
        "specs": {}
    },
    {
        "id": 1005,
        "category": "Laptop",
        "name": "HPVictus 16-R1032NT 9J234EA 8gb RTX4060 14. Nesil Intel I7-14700HX 32GB Ram 1tb SSD 16.1 Inç Fhd 144Hz Taşınabilir Bilgisayar",
        "brand": "HP",
        "price": 70875,
        "url": "https://www.hepsiburada.com/hp-victus-16-r1032nt-9j234ea-8gb-rtx4060-14-nesil-intel-i7-14700hx-32gb-ram-1tb-ssd-16-1-inc-fhd-144hz-tasinabilir-bilgisayar-pm-HBC00005OSLJL",
        "specs": {}
    },
    {
        "id": 1006,
        "category": "Laptop",
        "name": "LenovoLOQ AMD Ryzen 5 7235HS 16GB 512GB SSD RTX3050 Freedos 15.6\" FHD 83JC000QTR",
        "brand": "Lenovo",
        "price": 29529,
        "url": "https://www.hepsiburada.com/lenovo-loq-amd-ryzen-5-7235hs-16gb-512gb-ssd-rtx3050-freedos-15-6-fhd-tasinabilir-bilgisayar-83jc000qtr-pm-HBC0000771H5L",
        "specs": {}
    },
    {
        "id": 1007,
        "category": "Laptop",
        "name": "HuaweiMateBook D16 Intel Core i5-13420H 16GB 1TB SSD 16\" Windows 11 Gri Dizüstü Bilgisayar",
        "brand": "Huawei",
        "price": 32799,
        "url": "https://www.trendyol.com/huawei/matebook-d16-intel-core-i5-13420h-16gb-1tb-ssd-16-windows-11-gri-dizustu-bilgisayar-p-800344561",
        "specs": {}
    },
    {
        "id": 1008,
        "category": "Laptop",
        "name": "HPVictus Amd Ryzen 7-8845HS 16GB 1TB RTX4060 8GB Freedos 15.6\" FHD IPS 144Hz Laptop A05NGEA",
        "brand": "HP",
        "price": 40031,
        "url": "https://www.trendyol.com/hp/victus-amd-ryzen-7-8845hs-16gb-1tb-rtx4060-8gb-freedos-15-6-fhd-ips-144hz-laptop-a05ngea-p-733970853",
        "specs": {}
    },
    {
        "id": 1009,
        "category": "Laptop",
        "name": "LENOVOLOQ AMD Ryzen 7-7435HS 24GB 1TB SSD RTX4070 8GB GDDR6 FreeDOS 15.6\" FHD IPS 144Hz 115W Gaming Laptop",
        "brand": "Lenovo",
        "price": 51999,
        "url": "https://www.trendyol.com/lenovo/loq-amd-ryzen-7-7435hs-24gb-1tb-ssd-rtx4070-8gb-gddr6-freedos-15-6-fhd-ips-144hz-115w-gaming-laptop-p-898876689",
        "specs": {}
    },
    {
        "id": 1010,
        "category": "Laptop",
        "name": "Apple13\" MacBook Air: Apple M4 chip with 10-core CPU and 10-core GPU, 16GB, 512GB SSD - Gece Yarısı",
        "brand": "Apple",
        "price": 53999,
        "url": "https://www.trendyol.com/apple/13-macbook-air-apple-m4-chip-with-10-core-cpu-and-10-core-gpu-16gb-512gb-ssd-gece-yarisi-p-904728376",
        "specs": {}
    },
    {
        "id": 1011,
        "category": "Laptop",
        "name": "Apple14\" MacBook Pro: Apple M4 Pro chip with 14‑core CPU and 20‑core GPU, 24GB, 1TB SSD - Gümüş",
        "brand": "Apple",
        "price": 108999,
        "url": "https://www.trendyol.com/apple/14-macbook-pro-apple-m4-pro-chip-with-14-core-cpu-and-20-core-gpu-24gb-1tb-ssd-gumus-p-872448743",
        "specs": {}
    },
    {
        "id": 1012,
        "category": "Laptop",
        "name": "Apple13\" MacBook Air: Apple M4 chip with 10-core CPU and 10-core GPU, 16GB, 512GB SSD - Gümüş",
        "brand": "Apple",
        "price": 53849,
        "url": "https://www.trendyol.com/apple/13-macbook-air-apple-m4-chip-with-10-core-cpu-and-10-core-gpu-16gb-512gb-ssd-gumus-p-904728351",
        "specs": {}
    },
    {
        "id": 1013,
        "category": "Laptop",
        "name": "AcerNitro V 15 Intel Core I5 13420H 16GB Ddr5 512GB M.2 SSD Rtx 4050-6GB 60W Freedos 15.6\" Fhd IPS 144Hz Taşınabilir Bilgisayar NH.QNBEY.001-1",
        "brand": "Acer",
        "price": 37999,
        "url": "https://www.hepsiburada.com/acer-nitro-v-15-intel-core-i5-13420h-16gb-ddr5-512gb-m-2-ssd-rtx-4050-6gb-60w-freedos-15-6-fhd-ips-144hz-tasinabilir-bilgisayar-nh-qnbey-001-1-p-HBCV00008FHCJE",
        "specs": {}
    },

    # --- TELEFON (2001 - 2999) ---
    {
        "id": 2001,
        "category": "Telefon",
        "name": "AppleiPhone 17 512 GB Beyaz",
        "brand": "Apple",
        "price": 131999,
        "url": "https://www.hepsiburada.com/apple-iphone-17-512-gb-beyaz-p-HBCV00009Z3XDK?magaza=Hepsiburada",
        "specs": {
            "Dahili Hafıza": "512 GB",
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "Kamera Çözünürlüğü": "48 MP",
            "Parmak İzi Okuyucu": "Yok",
            "Arttırılabilir Hafıza": "Yok",
            "Şarj Girişi": "Type-C",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Kablosuz Şarj": "Var",
            "Katlanabilir": "Hayır",
            "Mobil Bağlantı Hızı": "5G",
            "Garanti Tipi": "Apple Türkiye Garantili",
            "Suya / Toza Dayanıklılık": "Var",
            "Ekran Boyutu": "6,3 inç",
            "Radyo": "Yok",
            "RAM  Kapasitesi": "8 GB RAM",
            "Yüz Tanıma": "Var",
            "Ekran Çözünürlüğü": "2622 x 1206",
            "Ekran Tipi": "Süper Retina",
            "Ön (Selfie) Kamera": "18 MP",
            "Telefon Modeli": "iPhone 17",
            "Pil Gücü": "3692 mAh",
            "Telefon Serisi": "iPhone 17",
            "Çift Hatlı": "Yok",
            "E-Sim": "Var",
            "Stok Adedi": "20 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV00009Z3XDK"
        }
    },
    {
        "id": 2002,
        "category": "Telefon",
        "name": "AppleiPhone 17 Pro 512 GB Gümüş",
        "brand": "Apple",
        "price": 131999,
        "url": "https://www.hepsiburada.com/apple-iphone-17-pro-512-gb-gumus-p-HBCV00009Z3XDN?magaza=Hepsiburada",
        "specs": {
            "Dahili Hafıza": "512 GB",
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "Kamera Çözünürlüğü": "48 MP",
            "Parmak İzi Okuyucu": "Yok",
            "Arttırılabilir Hafıza": "Yok",
            "Şarj Girişi": "Type-C",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Kablosuz Şarj": "Var",
            "Katlanabilir": "Hayır",
            "Mobil Bağlantı Hızı": "5G",
            "Garanti Tipi": "Apple Türkiye Garantili",
            "Suya / Toza Dayanıklılık": "Var",
            "Ekran Boyutu": "6,3 inç",
            "Radyo": "Yok",
            "RAM  Kapasitesi": "12 GB RAM",
            "Yüz Tanıma": "Var",
            "Ekran Çözünürlüğü": "2622 x 1206",
            "Ekran Tipi": "Süper Retina",
            "Ön (Selfie) Kamera": "18 MP",
            "Telefon Modeli": "iPhone 17 Pro",
            "Pil Gücü": "4252 mAh",
            "Telefon Serisi": "iPhone 17",
            "Çift Hatlı": "Yok",
            "E-Sim": "Var",
            "Stok Adedi": "50 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV00009Z3XDN"
        }
    },
    {
        "id": 2003,
        "category": "Telefon",
        "name": "AppleiPhone 13 128 GB Beyaz",
        "brand": "Apple",
        "price": 33800,
        "url": "https://www.hepsiburada.com/iphone-13-128-gb-beyaz-p-HBCV00000ODHHO",
        "specs": {}
    },
    {
        "id": 2004,
        "category": "Telefon",
        "name": "AppleiPhone 16 128GB Beyaz",
        "brand": "Apple",
        "price": 65950,
        "url": "https://www.hepsiburada.com/iphone-16-128gb-beyaz-p-HBCV00006Y4HFL",
        "specs": {
            "Ön (Selfie) Kamera": "8 - 12,9 MP",
            "Pil Gücü": "3561 mAh",
            "Mobil Bağlantı Hızı": "5G",
            "Suya / Toza Dayanıklılık": "Var",
            "Dahili Hafıza": "128 GB",
            "Pil Gücü Aralığı": "3500 - 3999 mAh",
            "Yüz Tanıma": "Var",
            "Ön (Selfie) Kamera Aralığı": "8 - 13,9 MP",
            "Şarj Girişi": "Type-C",
            "Radyo": "Yok",
            "Arttırılabilir Hafıza": "Yok",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Ekran Boyutu": "6,1 inç",
            "Kablosuz Şarj": "Var",
            "Parmak İzi Okuyucu": "Yok",
            "Garanti Tipi": "Apple Türkiye Garantili",
            "RAM  Kapasitesi": "8 GB RAM",
            "Katlanabilir": "Hayır",
            "Ekran Tipi": "OLED",
            "İşletim Sistemi": "iOS 18",
            "Ekran Çözünürlüğü": "2556 x 1179",
            "Telefon Serisi": "iPhone 16",
            "Telefon Modeli": "iPhone 16",
            "Stok Adedi": "500 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV00006Y4HFL"
        }
    },
    {
        "id": 2005,
        "category": "Telefon",
        "name": "Xiaomi14T Pro 256 GB 12 GB Ram (Xiaomi Türkiye Garantili) Mavi Titanyum",
        "brand": "Xiaomi",
        "price": 41999,
        "url": "https://www.hepsiburada.com/xiaomi-14t-pro-256-gb-12-gb-ram-xiaomi-turkiye-garantili-mavi-titanyum-p-HBCV00006YA8B2",
        "specs": {
            "Pil Gücü": "5000 mAh",
            "Mobil Bağlantı Hızı": "5G",
            "Suya / Toza Dayanıklılık": "Var",
            "Dahili Hafıza": "256 GB",
            "Pil Gücü Aralığı": "5000 mAh ve Üzeri",
            "Yüz Tanıma": "Var",
            "Şarj Girişi": "Type-C",
            "Radyo": "Var",
            "Arttırılabilir Hafıza": "256 GB'a kadar",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Ekran Boyutu": "6,67 inç",
            "Kablosuz Şarj": "Var",
            "Parmak İzi Okuyucu": "Var",
            "Katlanabilir": "Hayır",
            "Ekran Tipi": "AMOLED",
            "İşletim Sistemi": "Android 14",
            "Ön (Selfie) Kamera Aralığı": "20 MP ve Üzeri",
            "Garanti Tipi": "Resmi Distribütör Garantili",
            "RAM  Kapasitesi": "12 GB RAM",
            "Kamera Çözünürlüğü": "50 MP + 12 MP + 50 MP",
            "Ekran Çözünürlüğü": "1220 x 2712",
            "Telefon Modeli": "14T Pro",
            "Stok Adedi": "5 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV00006YA8B2"
        }
    },
    {
        "id": 2006,
        "category": "Telefon",
        "name": "AppleiPhone 15 128 GB Mavi",
        "brand": "Apple",
        "price": 54999,
        "url": "https://www.hepsiburada.com/iphone-15-128-gb-mavi-p-HBCV00004X9ZCK",
        "specs": {}
    },
    {
        "id": 2007,
        "category": "Telefon",
        "name": "AppleiPhone 17 Pro Max 2 Tb Gümüş",
        "brand": "Apple",
        "price": 209999,
        "url": "https://www.hepsiburada.com/apple-iphone-17-pro-max-2-tb-gumus-p-HBCV00009Z7YM8?magaza=Hepsiburada",
        "specs": {
            "Radyo": "Yok",
            "Dahili Hafıza": "1 TB",
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "RAM  Kapasitesi": "12 GB RAM",
            "Kamera Çözünürlüğü": "48 MP",
            "Parmak İzi Okuyucu": "Yok",
            "Arttırılabilir Hafıza": "Yok",
            "Şarj Girişi": "Type-C",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Kablosuz Şarj": "Var",
            "Katlanabilir": "Hayır",
            "Yüz Tanıma": "Var",
            "Mobil Bağlantı Hızı": "5G",
            "Ekran Çözünürlüğü": "2868 x 1320",
            "Garanti Tipi": "Apple Türkiye Garantili",
            "Suya / Toza Dayanıklılık": "Var",
            "Ekran Tipi": "Süper Retina",
            "Ekran Boyutu": "6,9 inç",
            "Ön (Selfie) Kamera": "18 MP",
            "Telefon Modeli": "iPhone 17 Pro Max",
            "Pil Gücü": "5088 mAh",
            "Telefon Serisi": "iPhone 17",
            "Çift Hatlı": "Yok",
            "E-Sim": "Var",
            "Stok Adedi": "20 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV00009Z7YM8"
        }
    },
    {
        "id": 2008,
        "category": "Telefon",
        "name": "XiaomiRedmi Note 14 Pro 256 GB 8 GB Ram (Xiaomi Türkiye Garantili) Siyah",
        "brand": "Xiaomi",
        "price": 16192,
        "url": "https://www.hepsiburada.com/redmi-note-14-pro-256-gb-8-gb-ram-xiaomi-turkiye-garantili-siyah-p-HBCV00007PLI1K",
        "specs": {
            "Pil Gücü Aralığı": "5000 mAh ve Üzeri",
            "Radyo": "Var",
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "Dahili Hafıza": "256 GB",
            "Kablosuz Şarj": "Yok",
            "Şarj Girişi": "Type-C",
            "Parmak İzi Okuyucu": "Var",
            "Göz Taraması": "Var",
            "RAM  Kapasitesi": "8 GB RAM",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Arttırılabilir Hafıza": "1 TB’a kadar",
            "Ön (Selfie) Kamera": "32 MP",
            "Ekran Tipi": "AMOLED",
            "Çift Hatlı": "Var",
            "Ekran Çözünürlüğü": "2400 x 1080",
            "Katlanabilir": "Hayır",
            "Ekran Boyutu": "6,67 inç",
            "Mobil Bağlantı Hızı": "4G",
            "Yüz Tanıma": "Var",
            "Garanti Tipi": "Resmi Distribütör Garantili",
            "Suya / Toza Dayanıklılık": "Var",
            "Ön (Selfie) Kamera Aralığı": "20 MP ve Üzeri",
            "Pil Gücü": "5500 mAh",
            "Stok Adedi": "1.000 adetten az",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV00007PLI1K"
        }
    },
    {
        "id": 2009,
        "category": "Telefon",
        "name": "XiaomiRedmi Note 14 Pro 5G 512 GB 12 GB Ram (Xiaomi Türkiye Garantili) Mor",
        "brand": "Xiaomi",
        "price": 27499,
        "url": "https://www.hepsiburada.com/redmi-note-14-pro-5g-512-gb-12-gb-ram-xiaomi-turkiye-garantili-mor-p-HBCV00007PN67Q",
        "specs": {
            "Pil Gücü Aralığı": "5000 mAh ve Üzeri",
            "Radyo": "Var",
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "Dahili Hafıza": "512 GB",
            "Kablosuz Şarj": "Yok",
            "Şarj Girişi": "Type-C",
            "Parmak İzi Okuyucu": "Var",
            "Göz Taraması": "Var",
            "RAM  Kapasitesi": "12 GB RAM",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Arttırılabilir Hafıza": "1 TB’a kadar",
            "Ön (Selfie) Kamera": "20 MP",
            "Ekran Tipi": "AMOLED",
            "Çift Hatlı": "Var",
            "Ekran Çözünürlüğü": "2400 x 1080",
            "Katlanabilir": "Hayır",
            "Ekran Boyutu": "6,67 inç",
            "Mobil Bağlantı Hızı": "5G",
            "Yüz Tanıma": "Var",
            "Garanti Tipi": "Resmi Distribütör Garantili",
            "Suya / Toza Dayanıklılık": "Var",
            "Ön (Selfie) Kamera Aralığı": "20 MP ve Üzeri",
            "Pil Gücü": "5110 mAh",
            "Stok Adedi": "50 adetten az",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV00007PN67Q"
        }
    },
    {
        "id": 2010,
        "category": "Telefon",
        "name": "AppleiPhone 17 Pro 256GB Abis",
        "brand": "Apple",
        "price": 118499,
        "url": "https://www.trendyol.com/apple/iphone-17-pro-256gb-abis-p-985256862",
        "specs": {}
    },
    {
        "id": 2011,
        "category": "Telefon",
        "name": "AppleiPhone 16 Pro Max 256GB Çöl Titanyum",
        "brand": "Apple",
        "price": 99999,
        "url": "https://www.trendyol.com/apple/iphone-16-pro-max-256gb-col-titanyum-p-857296109",
        "specs": {}
    },
    {
        "id": 2012,
        "category": "Telefon",
        "name": "SamsungGalaxy S25 Ultra 512 GB 12 GB Ram (Samsung Türkiye Garantili) Mavi Titanyum",
        "brand": "Samsung",
        "price": 79950,
        "url": "https://www.hepsiburada.com/samsung-galaxy-s25-ultra-512-gb-12-gb-ram-samsung-turkiye-garantili-mavi-titanyum-p-HBCV00007MIEMJ",
        "specs": {
            "Ön (Selfie) Kamera Aralığı": "8 - 13,9 MP",
            "Pil Gücü": "5000 mAh",
            "Pil Gücü Aralığı": "5000 mAh ve Üzeri",
            "Ön (Selfie) Kamera": "12 MP AF",
            "Ekran Çözünürlüğü": "1440 x 3120",
            "Kamera Çözünürlüğü": "200 MP + 12 MP + 10 MP + 10 MP",
            "RAM  Kapasitesi": "12 GB RAM",
            "Göz Taraması": "Var",
            "Yüz Tanıma": "Var",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Suya / Toza Dayanıklılık": "Var",
            "Şarj Girişi": "Type-C",
            "Çift Hatlı": "Var",
            "Kablosuz Şarj": "Var",
            "Ekran Tipi": "Dynamic AMOLED",
            "Mobil Bağlantı Hızı": "4G",
            "Garanti Tipi": "Samsung Türkiye Garantili",
            "Dahili Hafıza": "512 GB",
            "Parmak İzi Okuyucu": "Var",
            "Ekran Boyutu": "6,8 inç",
            "Katlanabilir": "Hayır",
            "Arttırılabilir Hafıza": "Yok",
            "Radyo": "Var",
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "Telefon Modeli": "Galaxy S25 Ultra",
            "Stok Adedi": "500 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV00007MIEMJ"
        }
    },
    {
        "id": 2013,
        "category": "Telefon",
        "name": "XiaomiRedmi Note 14 128 GB 8 GB Ram (Xiaomi Türkiye Garantili) Siyah",
        "brand": "Xiaomi",
        "price": 12180,
        "url": "https://www.hepsiburada.com/redmi-note-14-128-gb-8-gb-ram-xiaomi-turkiye-garantili-siyah-p-HBCV00007UCYSY",
        "specs": {
            "Pil Gücü Aralığı": "5000 mAh ve Üzeri",
            "Radyo": "Yok",
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "Dahili Hafıza": "128 GB",
            "Kablosuz Şarj": "Yok",
            "Şarj Girişi": "Type-C",
            "Parmak İzi Okuyucu": "Var",
            "Göz Taraması": "Yok",
            "RAM  Kapasitesi": "8 GB RAM",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Ekran Çözünürlüğü": "1080 x 2400",
            "Arttırılabilir Hafıza": "Var",
            "Ön (Selfie) Kamera": "20 MP",
            "Ekran Tipi": "AMOLED",
            "Çift Hatlı": "Var",
            "Katlanabilir": "Hayır",
            "Kamera Çözünürlüğü": "108 MP + 2 MP + 2 MP",
            "Ekran Boyutu": "6,67 inç",
            "Mobil Bağlantı Hızı": "4.5G",
            "Yüz Tanıma": "Var",
            "Suya / Toza Dayanıklılık": "Var",
            "Ön (Selfie) Kamera Aralığı": "20 MP ve Üzeri",
            "Garanti Tipi": "Xiaomi Türkiye Garantili",
            "Pil Gücü": "5500 mAh",
            "Kapasite": "128 GB",
            "Stok Adedi": "10.000 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV00007UCYSY"
        }
    },
    {
        "id": 2014,
        "category": "Telefon",
        "name": "SamsungGalaxy Z Fold7 512 GB 12 GB Ram (Samsung Türkiye Garantili) Gölge Mavisi",
        "brand": "Samsung",
        "price": 99000,
        "url": "https://www.hepsiburada.com/samsung-galaxy-z-fold7-512-gb-12-gb-ram-samsung-turkiye-garantili-golge-mavisi-p-HBCV000096X8RX",
        "specs": {
            "Pil Gücü": "4400 mAh",
            "Pil Gücü Aralığı": "4000 - 4999 mAh",
            "Kamera Çözünürlüğü": "50 MP + 12 MP + 10 MP",
            "RAM  Kapasitesi": "16 GB RAM",
            "Göz Taraması": "Var",
            "Yüz Tanıma": "Var",
            "Ekran Çözünürlüğü": "2160 x 3840",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Suya / Toza Dayanıklılık": "Var",
            "Şarj Girişi": "Type-C",
            "Ekran Boyutu": "7,93 inç",
            "Çift Hatlı": "Yok",
            "Kablosuz Şarj": "Var",
            "Ekran Tipi": "Dynamic AMOLED",
            "Mobil Bağlantı Hızı": "5G",
            "Garanti Tipi": "Samsung Türkiye Garantili",
            "Dahili Hafıza": "512 GB",
            "Parmak İzi Okuyucu": "Var",
            "Telefon Modeli": "Galaxy Z Fold 7",
            "Ön (Selfie) Kamera": "10 MP + 10 MP",
            "Katlanabilir": "Evet",
            "Ön (Selfie) Kamera Aralığı": "8 - 13,9 MP",
            "Arttırılabilir Hafıza": "Yok",
            "Radyo": "Yok",
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "Stok Adedi": "50 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV000096X8RX"
        }
    },
    {
        "id": 2015,
        "category": "Telefon",
        "name": "SamsungGalaxy A56 5g 256 GB 8 GB Ram (Samsung Türkiye Garantili) Siyah",
        "brand": "Samsung",
        "price": 22899,
        "url": "https://www.hepsiburada.com/samsung-galaxy-a56-5g-256-gb-8-gb-ram-samsung-turkiye-garantili-siyah-p-HBCV000088BXWW",
        "specs": {
            "NFC (Yakın Alan İletişimi)": "Var",
            "Suya / Toza Dayanıklılık": "Yok",
            "Ön (Selfie) Kamera Aralığı": "8 - 13,9 MP",
            "Çift Hatlı": "Var",
            "Şarj Girişi": "Type-C",
            "Pil Gücü": "5000 mAh",
            "Ön (Selfie) Kamera": "12 MP AF",
            "Pil Gücü Aralığı": "5000 - 9000 mAh",
            "Kablosuz Şarj": "Yok",
            "Ekran Tipi": "Süper AMOLED",
            "Ekran Çözünürlüğü": "1080 x 2340",
            "Mobil Bağlantı Hızı": "5G",
            "Garanti Tipi": "Samsung Türkiye Garantili",
            "Dahili Hafıza": "256 GB",
            "Kamera Çözünürlüğü": "20 MP ve Üzeri",
            "Parmak İzi Okuyucu": "Var",
            "RAM  Kapasitesi": "8 GB RAM",
            "Ekran Boyutu": "6,7 inç",
            "Katlanabilir": "Hayır",
            "Arttırılabilir Hafıza": "Yok",
            "Göz Taraması": "Yok",
            "Yüz Tanıma": "Var",
            "Radyo": "Var",
            "Telefon Modeli": "Galaxy A56",
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "Stok Adedi": "1.000 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV000088BXWW"
        }
    },
    {
        "id": 2016,
        "category": "Telefon",
        "name": "SamsungGalaxy A16 128 GB 6 GB Ram (Samsung Türkiye Garantili) Gri",
        "brand": "Samsung",
        "price": 10998,
        "url": "https://www.hepsiburada.com/samsung-galaxy-a16-128-gb-6-gb-ram-samsung-turkiye-garantili-gri-p-HBCV00006Y952I",
        "specs": {
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "Göz Taraması": "Yok",
            "Boyutlar": "6.7'' 2340x1080 (FHD+)  Dynamic Amoled 2x Display 120Hz 1200 Nit",
            "Pil Gücü": "5000 mAh",
            "Suya / Toza Dayanıklılık": "Yok",
            "Dahili Hafıza": "Yok",
            "Pil Gücü Aralığı": "5000 mAh ve Üzeri",
            "Ön (Selfie) Kamera Aralığı": "8 - 13,9 MP",
            "Şarj Girişi": "Type-C",
            "Radyo": "Yok",
            "Ekran Çözünürlüğü": "1080 x 2340",
            "Arttırılabilir Hafıza": "Yok",
            "NFC (Yakın Alan İletişimi)": "Var",
            "Ekran Boyutu": "6,71 inç",
            "Kablosuz Şarj": "Yok",
            "Parmak İzi Okuyucu": "Var",
            "RAM  Kapasitesi": "6 GB RAM",
            "Çift Hatlı": "Yok",
            "Katlanabilir": "Hayır",
            "Ekran Tipi": "Süper AMOLED",
            "İşletim Sistemi": "Android 14",
            "Telefon Modeli": "Galaxy A16",
            "Garanti Tipi": "Samsung Türkiye Garantili",
            "Mobil Bağlantı Hızı": "LTE",
            "Yüz Tanıma": "Var",
            "Stok Adedi": "1.000 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV00006Y952I"
        }
    },
    {
        "id": 2017,
        "category": "Telefon",
        "name": "AppleiPhone 17 Pro Max 512GB Kozmik Turuncu",
        "brand": "Apple",
        "price": 151999,
        "url": "https://www.trendyol.com/apple/iphone-17-pro-max-512gb-kozmik-turuncu-p-985256866",
        "specs": {}
    },
    {
        "id": 2018,
        "category": "Telefon",
        "name": "AppleiPhone 16 128GB Beyaz",
        "brand": "Apple",
        "price": 58999,
        "url": "https://www.trendyol.com/apple/iphone-16-128gb-beyaz-p-857296082",
        "specs": {}
    },
    {
        "id": 2019,
        "category": "Telefon",
        "name": "AppleiPhone Air 256GB Uzay Siyahı",
        "brand": "Apple",
        "price": 97998,
        "url": "https://www.trendyol.com/apple/iphone-air-256gb-uzay-siyahi-p-985256818",
        "specs": {}
    },
    {
        "id": 2020,
        "category": "Telefon",
        "name": "AppleiPhone 17 256GB Siyah",
        "brand": "Apple",
        "price": 77999,
        "url": "https://www.trendyol.com/apple/iphone-17-256gb-siyah-p-985256842",
        "specs": {}
    },
    {
        "id": 2021,
        "category": "Telefon",
        "name": "AppleiPhone 15 128 GB Mavi",
        "brand": "Apple",
        "price": 48749,
        "url": "https://www.trendyol.com/apple/iphone-15-128-gb-mavi-p-762254881",
        "specs": {}
    },
    {
        "id": 2022,
        "category": "Telefon",
        "name": "SamsungGalaxy A36 5g 256 GB 8 GB Ram (Samsung Türkiye Garantili) Siyah",
        "brand": "Samsung",
        "price": 18400,
        "url": "https://www.hepsiburada.com/samsung-galaxy-a36-5g-256-gb-8-gb-ram-samsung-turkiye-garantili-siyah-p-HBCV000088BXFB",
        "specs": {
            "NFC (Yakın Alan İletişimi)": "Var",
            "Suya / Toza Dayanıklılık": "Yok",
            "Ön (Selfie) Kamera Aralığı": "8 - 13,9 MP",
            "Çift Hatlı": "Var",
            "Şarj Girişi": "Type-C",
            "Pil Gücü": "5000 mAh",
            "Ön (Selfie) Kamera": "12 MP AF",
            "Pil Gücü Aralığı": "5000 - 9000 mAh",
            "Kablosuz Şarj": "Yok",
            "Ekran Tipi": "Süper AMOLED",
            "Ekran Çözünürlüğü": "1080 x 2340",
            "Mobil Bağlantı Hızı": "5G",
            "Garanti Tipi": "Samsung Türkiye Garantili",
            "Dahili Hafıza": "256 GB",
            "Kamera Çözünürlüğü": "20 MP ve Üzeri",
            "Parmak İzi Okuyucu": "Var",
            "RAM  Kapasitesi": "8 GB RAM",
            "Ekran Boyutu": "6,7 inç",
            "Katlanabilir": "Hayır",
            "Arttırılabilir Hafıza": "Yok",
            "Göz Taraması": "Yok",
            "Yüz Tanıma": "Var",
            "Radyo": "Var",
            "Telefon Modeli": "Galaxy A36",
            "GPS (Küresel Konumlama Sistemi)": "Var",
            "Stok Adedi": "10.000 adetten az",
            "Garanti Süresi (Ay)": "24",
            "Yurt Dışı Satış": "Yok",
            "Stok Kodu": "HBCV000088BXFB"
        }
    },
    {
        "id": 2023,
        "category": "Telefon",
        "name": "AppleiPhone 17 Pro Max 256GB Kozmik Turuncu",
        "brand": "Apple",
        "price": 139799,
        "url": "https://www.trendyol.com/apple/iphone-17-pro-max-256gb-kozmik-turuncu-p-985256825",
        "specs": {}
    },
    {
        "id": 2024,
        "category": "Telefon",
        "name": "XiaomiRedmi Note 14 Pro 12GB RAM 512GB ROM, Mor (Xiaomi Türkiye Garantili)",
        "brand": "Xiaomi",
        "price": 18199,
        "url": "https://www.trendyol.com/xiaomi/redmi-note-14-pro-12gb-ram-512gb-rom-mor-xiaomi-turkiye-garantili-p-891692668",
        "specs": {}
    },
    {
        "id": 2025,
        "category": "Telefon",
        "name": "Xiaomi14T Pro 512 GB Gri (Xiaomi Türkiye Garantili)",
        "brand": "Xiaomi",
        "price": 39419,
        "url": "https://www.trendyol.com/xiaomi/14t-pro-512-gb-gri-xiaomi-turkiye-garantili-p-963232257",
        "specs": {}
    },
    {
        "id": 2026,
        "category": "Telefon",
        "name": "SamsungGalaxy S24 Ultra 256 GB Titanyum Gri (Samsung Türkiye Garantili)",
        "brand": "Samsung",
        "price": 59949,
        "url": "https://www.trendyol.com/samsung/galaxy-s24-ultra-256-gb-titanyum-gri-samsung-turkiye-garantili-p-792557583",
        "specs": {}
    },
    {
        "id": 2027,
        "category": "Telefon",
        "name": "OppoA60 Nfc 16 Gb Ram (8 8 DİNAMİK RAM) 256 Gb Gece Moru Kablolu Kulaklık",
        "brand": "OPPO",
        "price": 13600,
        "url": "https://www.trendyol.com/oppo/a60-nfc-16-gb-ram-8-8-dinamik-ram-256-gb-gece-moru-kablolu-kulaklik-p-875669278",
        "specs": {}
    },
    {
        "id": 2028,
        "category": "Telefon",
        "name": "XiaomiRedmi Note 14 Pro 12GB+512GB Siyah(Xiaomi Türkiye Garantili)",
        "brand": "Xiaomi",
        "price": 18199,
        "url": "https://www.trendyol.com/xiaomi/redmi-note-14-pro-12gb-512gb-siyah-xiaomi-turkiye-garantili-p-891692667",
        "specs": {}
    },
    {
        "id": 2029,
        "category": "Telefon",
        "name": "XiaomiRedmi Note 14 8+256 Siyah(Xiaomi Türkiye Garantili)",
        "brand": "Xiaomi",
        "price": 11999,
        "url": "https://www.trendyol.com/xiaomi/redmi-note-14-8-256-siyah-xiaomi-turkiye-garantili-p-891692672",
        "specs": {}
    },
    {
        "id": 2030,
        "category": "Telefon",
        "name": "SamsungGalaxy A16 6 GB RAM 128 GB Gri (Samsung Türkiye Garantili)",
        "brand": "Samsung",
        "price": 9699,
        "url": "https://www.trendyol.com/samsung/galaxy-a16-6-gb-ram-128-gb-gri-samsung-turkiye-garantili-p-879171111",
        "specs": {}
    },
    {
        "id": 2031,
        "category": "Telefon",
        "name": "XiaomiRedmi 13 8 GB RAM 256 GB Siyah Cep Telefonu (Xiaomi Türkiye Garantili)",
        "brand": "Xiaomi",
        "price": 8559,
        "url": "https://www.trendyol.com/xiaomi/redmi-13-8-gb-ram-256-gb-siyah-cep-telefonu-xiaomi-turkiye-garantili-p-836127382",
        "specs": {}
    },
    {
        "id": 2032,
        "category": "Telefon",
        "name": "SamsungGalaxy S25 Fe 256 GB 8 GB Ram (Samsung Türkiye Garantili) Buz Mavisi",
        "brand": "Samsung",
        "price": 22749,
        "url": "https://www.hepsiburada.com/samsung-galaxy-s25-fe-256-gb-8-gb-ram-samsung-turkiye-garantili-buz-mavisi-p-HBCV00009S5CRQ?magaza=Hepsiburada",
        "specs": {}
    },
    {
        "id": 2033,
        "category": "Telefon",
        "name": "SamsungGalaxy S25 Ultra 512 GB Titanyum Siyah (Samsung Türkiye Garantili)",
        "brand": "Samsung",
        "price": 72199,
        "url": "https://www.trendyol.com/samsung/galaxy-s25-ultra-512-gb-titanyum-siyah-samsung-turkiye-garantili-p-889950721",
        "specs": {}
    },

    # --- MASAÜSTÜ (3001 - 3999) ---
    {
        "id": 3001,
        "category": "Masaüstü",
        "name": "KUARK-POLAR",
        "brand": "ITOPYA",
        "price": 41620,
        "url": "https://www.itopya.com/kuark-polar-intel-core-i5-14400f-msi-geforce-rtx-5060-8gb-16gb-ddr5-500gb-nvme-m2-ssd-gef_h30711",
        "specs": {
            "Özellik 1": "INTEL Core i5 14400F",
            "Özellik 2": "MSI GeForce RTX 5060 8GB",
            "Özellik 3": "16GB DDR5",
            "Özellik 4": "500GB NVME M.2 SSD",
            "Özellik 5": "GeForce RTX Sistem Tavsiyesi"
        }
    },
    {
        "id": 3002,
        "category": "Masaüstü",
        "name": "EMIN CITAK",
        "brand": "ITOPYA",
        "price": 34999,
        "url": "https://www.itopya.com/emin-citak-amd-ryzen-5-7500f-xfx-radeon-rx-9060-xt-oc-8gb-16gb-ddr5-500gb-nvme-m2-ssd-amd_h30710",
        "specs": {
            "Özellik 1": "AMD Ryzen 5 7500F",
            "Özellik 2": "XFX Radeon RX 9060 XT OC 8GB",
            "Özellik 3": "16GB DDR5",
            "Özellik 4": "500GB NVME M.2 SSD",
            "Özellik 5": "AMD Radeon Sistem Tavsiyesi"
        }
    },
    {
        "id": 3003,
        "category": "Masaüstü",
        "name": "RN DONANIM",
        "brand": "ITOPYA",
        "price": 29999,
        "url": "https://www.itopya.com/rn-donanim-intel-core-i5-14400f-inno3d-geforce-rtx-5060-twin-x2-8gb-16gb-ddr5-500gb-nvme-m2_h30709",
        "specs": {
            "Özellik 1": "INTEL Core i5 14400F",
            "Özellik 2": "INNO3D GeForce RTX 5060 TWIN X2 8GB",
            "Özellik 3": "16GB DDR5",
            "Özellik 4": "500GB NVME M.2 SSD",
            "Özellik 5": "GeForce RTX Sistem Tavsiyesi"
        }
    },
    {
        "id": 3004,
        "category": "Masaüstü",
        "name": "IMAGINE-9060",
        "brand": "ITOPYA",
        "price": 33640,
        "url": "https://www.itopya.com/imagine-9060-amd-ryzen-5-7500f-xfx-swift-radeon-rx-9060-8gb-16gb-ddr5-500gb-nvme-m2-ssd-a_h30707",
        "specs": {
            "Özellik 1": "AMD Ryzen 5 7500F",
            "Özellik 2": "XFX Swift Radeon RX 9060 8GB",
            "Özellik 3": "16GB DDR5",
            "Özellik 4": "500GB NVME M.2 SSD",
            "Özellik 5": "AMD Radeon Sistem Tavsiyesi"
        }
    },
    {
        "id": 3005,
        "category": "Masaüstü",
        "name": "DRAGON-5060T V10",
        "brand": "ITOPYA",
        "price": 33202,
        "url": "https://www.itopya.com/dragon-5060t-v10-amd-ryzen-5-7500f-msi-geforce-rtx-5060-ti-8gb-16gb-ddr5-500gb-nvme-m2-ssd-_h30689",
        "specs": {
            "Özellik 1": "AMD Ryzen 5 7500F",
            "Özellik 2": "MSI GeForce RTX 5060 Ti 8GB",
            "Özellik 3": "16GB DDR5",
            "Özellik 4": "500GB NVME M.2 SSD",
            "Özellik 5": "GeForce RTX Sistem Tavsiyesi"
        }
    },
    {
        "id": 3006,
        "category": "Masaüstü",
        "name": "ALI BICIM-STARS/INTEL Core i7 14700KF",
        "brand": "Intel",
        "price": 79505,
        "url": "https://www.itopya.com/ali-bicim-starsintel-core-i7-14700kf-asus-geforce-rtx-5070-12gb-32gb-ddr5-1tb-m2-ssd-gefor_h30617",
        "specs": {
            "Özellik 1": "ASUS GeForce RTX 5070 12GB",
            "Özellik 2": "32GB DDR5",
            "Özellik 3": "1TB M.2 SSD",
            "Özellik 4": "Geforce RTX Sistem Tavsiyesi"
        }
    },
    {
        "id": 3007,
        "category": "Masaüstü",
        "name": "MODART-BTS",
        "brand": "ITOPYA",
        "price": 55448,
        "url": "https://www.itopya.com/modart-bts-intel-core-i5-14600kf-asus-dual-geforce-rtx-5070-12gb-32gb-ddr5-1tb-m2-ssd-gef_h30686",
        "specs": {
            "Özellik 1": "INTEL Core i5 14600KF",
            "Özellik 2": "ASUS Dual GeForce RTX 5070 12GB",
            "Özellik 3": "32GB DDR5",
            "Özellik 4": "1TB M.2 SSD",
            "Özellik 5": "Geforce RTX Sistem Tavsiyesi"
        }
    },
    {
        "id": 3008,
        "category": "Masaüstü",
        "name": "ALI BICIM-KANKS",
        "brand": "ITOPYA",
        "price": 40003,
        "url": "https://www.itopya.com/ali-bicim-kanks-intel-core-i5-14600k-asus-geforce-rtx-5060-8gb-16gb-ddr5-1tb-m2-ssd-gefor_h30618",
        "specs": {
            "Özellik 1": "INTEL Core i5 14600K",
            "Özellik 2": "ASUS GeForce RTX 5060 8GB",
            "Özellik 3": "16GB DDR5",
            "Özellik 4": "1TB M.2 SSD",
            "Özellik 5": "Geforce RTX Sistem Tavsiyesi"
        }
    },
    {
        "id": 3009,
        "category": "Masaüstü",
        "name": "RADEON-BTS /AMD Ryzen 7 7800X3D/ASUS Radeon RX 9070 XT 16GB/32GB DDR5/1TB M.2 SSD/AMD Radeon Sistem Tavsiyesi",
        "brand": "Asus",
        "price": 62999,
        "url": "https://www.itopya.com/radeon-bts-amd-ryzen-7-7800x3dasus-radeon-rx-9070-xt-16gb32gb-ddr51tb-m2-ssdamd-radeon-sistem-_h30610",
        "specs": {}
    },
    {
        "id": 3010,
        "category": "Masaüstü",
        "name": "ALI BICIM-KINGS /INTEL Core Ultra 9 285K/ ASUS GeForce RTX 5090 32GB",
        "brand": "Asus",
        "price": 230000,
        "url": "https://www.itopya.com/ali-bicim-kings-intel-core-ultra-9-285k-asus-geforce-rtx-5090-32gb-48gb-ddr5-2tbm2-ssdgeforc_h30616",
        "specs": {
            "Özellik 1": "48GB DDR5",
            "Özellik 2": "2TBM.2 SSD/Geforce RTX Sistem Tavsiyesi"
        }
    },
    {
        "id": 3011,
        "category": "Masaüstü",
        "name": "FREKANS-A9",
        "brand": "ITOPYA",
        "price": 65557,
        "url": "https://www.itopya.com/frekans-a9-intel-core-ultra-5-245kf-msi-geforce-rtx-5070-12gb-32gb-ddr5-1tb-nvme-m2-ssd-g_h30609",
        "specs": {
            "Özellik 1": "INTEL Core Ultra 5 245KF",
            "Özellik 2": "MSI GeForce RTX 5070 12GB",
            "Özellik 3": "32GB DDR5",
            "Özellik 4": "1TB NVME M.2 SSD",
            "Özellik 5": "GeForce RTX Sistem Tavsiyesi"
        }
    }
]